### PR TITLE
Update ARepeatedAttackAI.cs

### PR DESCRIPTION
**Pull request by timmiedinnie**
In stead of ending attack in the next  counter loop, just end when the last attack is made.

### CODE REVIEW

**Comment by 12joan** [comment]
Thanks for the PR! 😄

I've simplified the logic a bit more and fixed the coding style, but good catch!

**Comment by 12joan** [comment]
@timmiedinnie Incidentally, we're currently looking for playtesters for this game. Here's the link if you're interested. https://anderbell.studio/playtesting/

**Comment by timmiedinnie** [comment]
I'm very interested, also I don't mind helping out on with some stuff. Let me know.

**Comment by 12joan** [comment]
> I don't mind helping out on with some stuff

That would be a great help once we resume development on the game. If you join our Discord server (there's an invite link in the playtesting guide), we'll be sure to let you know if there are any coding tasks we could use you help with.

**Pull request merged**
